<?php

declare(strict_types=1);

namespace App\Services\Central\Tenants;

use App\Services\Central\Settings\SettingService;

final class TenantSettings
{
    public function __construct(
        private readonly SettingService $settings,
    )
    {
    }

    public function defaultTrialDays(): int
    {
        return $this->integer('tenant.default_trial_days', 14, 0, 365);
    }

    private function integer(string $key, int $default, int $minimum, int $maximum): int
    {
        $value = filter_var($this->settings->get($key, $default), FILTER_VALIDATE_INT);

        if ($value === false) {
            return $default;
        }

        return max($minimum, min($maximum, $value));
    }

    public function ownerInviteTtlHours(): int
    {
        return $this->integer('tenant.owner_invite_ttl_hours', 72, 1, 720);
    }

    public function signupIntentTtlHours(): int
    {
        return $this->integer('tenant.signup_intent_ttl_hours', 2, 1, 168);
    }

    public function autoGenerateDomain(): bool
    {
        return $this->boolean('tenant.auto_generate_domain', true);
    }

    private function boolean(string $key, bool $default): bool
    {
        $value = filter_var(
            $this->settings->get($key, $default),
            FILTER_VALIDATE_BOOLEAN,
            FILTER_NULL_ON_FAILURE,
        );

        return $value ?? $default;
    }

    public function defaultForceHttps(): bool
    {
        return $this->boolean('tenant.default_force_https', true);
    }

    public function allowCustomDomains(): bool
    {
        return $this->boolean('tenant.allow_custom_domains', true);
    }
}
