<?php

declare(strict_types=1);

namespace Database\Seeders\Central;

use App\Enums\Central\SettingGroup;
use App\Enums\Central\SettingType;
use App\Models\Central\Setting;
use App\Services\Central\Settings\SettingService;
use Illuminate\Database\Seeder;

class SettingSeeder extends Seeder
{
    public function run(): void
    {
        Setting::query()
            ->where(function ($query): void {
                $query->where('group', 'smtp')
                    ->orWhere('key', 'like', 'smtp.%');
            })
            ->delete();

        foreach ($this->definitions() as $definition) {
            Setting::query()->updateOrCreate(
                ['key' => $definition['key']],
                $definition,
            );
        }

        Setting::query()
            ->where('key', 'billing.mode')
            ->whereNotIn('value', ['test', 'live'])
            ->update([
                'value' => 'test',
                'options' => ['test', 'live'],
            ]);

        app(SettingService::class)->forgetCache();
    }

    /**
     * @return list<array<string, mixed>>
     */
    private function definitions(): array
    {
        return [
            [
                'group' => SettingGroup::Platform,
                'key' => 'platform.name',
                'label' => 'Platform Name',
                'description' => 'Public brand name for the landlord console.',
                'type' => SettingType::STRING,
                'value' => 'Multi Tenant API',
                'default_value' => ['value' => 'Multi Tenant API'],
                'is_public' => true,
                'sort_order' => 1,
            ],
            [
                'group' => SettingGroup::Platform,
                'key' => 'platform.support_email',
                'label' => 'Support Email',
                'description' => 'Primary support contact address.',
                'type' => SettingType::EMAIL,
                'value' => 'support@example.com',
                'default_value' => ['value' => 'support@example.com'],
                'is_public' => true,
                'sort_order' => 2,
            ],
            [
                'group' => SettingGroup::Mail,
                'key' => 'mail.mailer',
                'label' => 'Mail Driver',
                'description' => 'How the platform sends email. Use log for local development, smtp for real delivery.',
                'type' => SettingType::SELECT,
                'value' => 'log',
                'default_value' => ['value' => 'log'],
                'options' => ['log', 'smtp', 'array'],
                'sort_order' => 1,
            ],
            [
                'group' => SettingGroup::Mail,
                'key' => 'mail.from_address',
                'label' => 'From Address',
                'description' => 'Default sender email address for platform mail.',
                'type' => SettingType::EMAIL,
                'value' => 'hello@example.com',
                'default_value' => ['value' => 'hello@example.com'],
                'sort_order' => 2,
            ],
            [
                'group' => SettingGroup::Mail,
                'key' => 'mail.from_name',
                'label' => 'From Name',
                'description' => 'Default sender display name.',
                'type' => SettingType::STRING,
                'value' => 'Multi Tenant API',
                'default_value' => ['value' => 'Multi Tenant API'],
                'sort_order' => 3,
            ],
            [
                'group' => SettingGroup::Mail,
                'key' => 'mail.host',
                'label' => 'SMTP Host',
                'description' => 'SMTP server hostname. Only used when Mail Driver is smtp.',
                'type' => SettingType::STRING,
                'value' => null,
                'default_value' => ['value' => null],
                'sort_order' => 4,
            ],
            [
                'group' => SettingGroup::Mail,
                'key' => 'mail.port',
                'label' => 'SMTP Port',
                'description' => 'SMTP port (typically 587 for TLS or 465 for SSL).',
                'type' => SettingType::INTEGER,
                'value' => '587',
                'default_value' => ['value' => 587],
                'sort_order' => 5,
            ],
            [
                'group' => SettingGroup::Mail,
                'key' => 'mail.username',
                'label' => 'SMTP Username',
                'type' => SettingType::STRING,
                'value' => null,
                'default_value' => ['value' => null],
                'sort_order' => 6,
            ],
            [
                'group' => SettingGroup::Mail,
                'key' => 'mail.password',
                'label' => 'SMTP Password',
                'type' => SettingType::ENCRYPTED,
                'value' => null,
                'default_value' => ['value' => null],
                'is_encrypted' => true,
                'sort_order' => 7,
            ],
            [
                'group' => SettingGroup::Mail,
                'key' => 'mail.scheme',
                'label' => 'SMTP Scheme',
                'description' => 'Leave empty for STARTTLS (port 587). Use smtps for implicit SSL (port 465).',
                'type' => SettingType::SELECT,
                'value' => '',
                'default_value' => ['value' => ''],
                'options' => ['', 'smtp', 'smtps'],
                'sort_order' => 8,
            ],
            [
                'group' => SettingGroup::Storage,
                'key' => 'storage.default_disk',
                'label' => 'Default Disk',
                'description' => 'Filesystem disk used for uploads and platform storage.',
                'type' => SettingType::SELECT,
                'value' => 'local',
                'default_value' => ['value' => 'local'],
                'options' => ['local', 's3'],
                'sort_order' => 1,
            ],
            [
                'group' => SettingGroup::Storage,
                'key' => 'storage.s3_key',
                'label' => 'S3 Access Key',
                'description' => 'AWS access key ID. Only used when Default Disk is s3.',
                'type' => SettingType::STRING,
                'value' => null,
                'default_value' => ['value' => null],
                'sort_order' => 2,
            ],
            [
                'group' => SettingGroup::Storage,
                'key' => 'storage.s3_secret',
                'label' => 'S3 Secret Key',
                'description' => 'AWS secret access key. Stored encrypted.',
                'type' => SettingType::ENCRYPTED,
                'value' => null,
                'default_value' => ['value' => null],
                'is_encrypted' => true,
                'sort_order' => 3,
            ],
            [
                'group' => SettingGroup::Storage,
                'key' => 'storage.s3_region',
                'label' => 'S3 Region',
                'type' => SettingType::STRING,
                'value' => 'us-east-1',
                'default_value' => ['value' => 'us-east-1'],
                'sort_order' => 4,
            ],
            [
                'group' => SettingGroup::Storage,
                'key' => 'storage.s3_bucket',
                'label' => 'S3 Bucket',
                'type' => SettingType::STRING,
                'value' => null,
                'default_value' => ['value' => null],
                'sort_order' => 5,
            ],
            [
                'group' => SettingGroup::Storage,
                'key' => 'storage.s3_url',
                'label' => 'S3 URL',
                'description' => 'Optional public base URL for the bucket.',
                'type' => SettingType::URL,
                'value' => null,
                'default_value' => ['value' => null],
                'sort_order' => 6,
            ],
            [
                'group' => SettingGroup::Storage,
                'key' => 'storage.s3_endpoint',
                'label' => 'S3 Endpoint',
                'description' => 'Optional custom endpoint (MinIO, R2-compatible, etc.).',
                'type' => SettingType::URL,
                'value' => null,
                'default_value' => ['value' => null],
                'sort_order' => 7,
            ],
            [
                'group' => SettingGroup::Storage,
                'key' => 'storage.s3_use_path_style_endpoint',
                'label' => 'Use Path-Style Endpoint',
                'description' => 'Enable for MinIO and some S3-compatible providers.',
                'type' => SettingType::BOOLEAN,
                'value' => '0',
                'default_value' => ['value' => false],
                'sort_order' => 8,
            ],
            [
                'group' => SettingGroup::Localization,
                'key' => 'localization.default_locale',
                'label' => 'Default Locale',
                'type' => SettingType::STRING,
                'value' => 'en',
                'default_value' => ['value' => 'en'],
                'is_public' => true,
                'sort_order' => 1,
            ],
            [
                'group' => SettingGroup::Localization,
                'key' => 'localization.default_timezone',
                'label' => 'Default Timezone',
                'type' => SettingType::TIMEZONE,
                'value' => 'UTC',
                'default_value' => ['value' => 'UTC'],
                'is_public' => true,
                'sort_order' => 2,
            ],
            [
                'group' => SettingGroup::Localization,
                'key' => 'localization.default_currency',
                'label' => 'Default Currency',
                'type' => SettingType::STRING,
                'value' => 'USD',
                'default_value' => ['value' => 'USD'],
                'is_public' => true,
                'sort_order' => 3,
            ],
            [
                'group' => SettingGroup::Security,
                'key' => 'security.require_2fa',
                'label' => 'Require Two-Factor Auth',
                'type' => SettingType::BOOLEAN,
                'value' => '0',
                'default_value' => ['value' => false],
                'sort_order' => 1,
            ],
            [
                'group' => SettingGroup::Maintenance,
                'key' => 'maintenance.enabled',
                'label' => 'Maintenance Mode',
                'type' => SettingType::BOOLEAN,
                'value' => '0',
                'default_value' => ['value' => false],
                'is_public' => true,
                'sort_order' => 1,
            ],
            [
                'group' => SettingGroup::Api,
                'key' => 'api.rate_limit_per_minute',
                'label' => 'API Rate Limit',
                'type' => SettingType::INTEGER,
                'value' => '60',
                'default_value' => ['value' => 60],
                'sort_order' => 1,
            ],
            [
                'group' => SettingGroup::Media,
                'key' => 'media.max_upload_mb',
                'label' => 'Max Upload Size (MB)',
                'type' => SettingType::INTEGER,
                'value' => '10',
                'default_value' => ['value' => 10],
                'sort_order' => 1,
            ],
            [
                'group' => SettingGroup::Cdn,
                'key' => 'cdn.url',
                'label' => 'CDN URL',
                'type' => SettingType::URL,
                'value' => null,
                'default_value' => ['value' => null],
                'sort_order' => 1,
            ],
            [
                'group' => SettingGroup::Ai,
                'key' => 'ai.default_provider',
                'label' => 'Default AI Provider',
                'type' => SettingType::SELECT,
                'value' => 'openai',
                'default_value' => ['value' => 'openai'],
                'options' => ['openai', 'gemini', 'anthropic', 'grok'],
                'sort_order' => 1,
            ],
            [
                'group' => SettingGroup::Oauth,
                'key' => 'oauth.google_enabled',
                'label' => 'Google OAuth Enabled',
                'type' => SettingType::BOOLEAN,
                'value' => '0',
                'default_value' => ['value' => false],
                'sort_order' => 1,
            ],
            [
                'group' => SettingGroup::Captcha,
                'key' => 'captcha.enabled',
                'label' => 'Captcha Enabled',
                'type' => SettingType::BOOLEAN,
                'value' => '0',
                'default_value' => ['value' => false],
                'sort_order' => 1,
            ],
            [
                'group' => SettingGroup::Backups,
                'key' => 'backups.retention_days',
                'label' => 'Backup Retention Days',
                'type' => SettingType::INTEGER,
                'value' => '30',
                'default_value' => ['value' => 30],
                'sort_order' => 1,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.mode',
                'label' => 'Payment Mode',
                'description' => 'Test uses provider sandbox/test credentials. Live uses production credentials. Both call real provider APIs.',
                'type' => SettingType::SELECT,
                'value' => $this->normalizePaymentMode((string) config('payments.mode', 'test')),
                'default_value' => ['value' => $this->normalizePaymentMode((string) config('payments.mode', 'test'))],
                'options' => ['test', 'live'],
                'is_public' => false,
                'sort_order' => 1,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.default_gateway',
                'label' => 'Default Payment Gateway',
                'description' => 'Fallback gateway when a plan currency is not mapped below. Customers never pick this — the platform chooses by currency.',
                'type' => SettingType::SELECT,
                'value' => (string) config('payments.default', 'paystack'),
                'default_value' => ['value' => (string) config('payments.default', 'paystack')],
                'options' => ['paystack', 'flutterwave', 'stripe', 'manual'],
                'is_public' => false,
                'sort_order' => 2,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.gateway_by_currency',
                'label' => 'Gateway By Currency',
                'description' => 'Deprecated: prefer payment_gateways catalog routing. Map ISO currencies to gateways. African currencies typically use Paystack/Flutterwave; USD/EUR/GBP use Stripe.',
                'type' => SettingType::JSON,
                'value' => json_encode([
                    'NGN' => 'paystack',
                    'GHS' => 'paystack',
                    'KES' => 'flutterwave',
                    'ZAR' => 'paystack',
                    'UGX' => 'flutterwave',
                    'TZS' => 'flutterwave',
                    'XOF' => 'flutterwave',
                    'XAF' => 'flutterwave',
                    'USD' => 'stripe',
                    'EUR' => 'stripe',
                    'GBP' => 'stripe',
                    'CAD' => 'stripe',
                    'AUD' => 'stripe',
                ], JSON_THROW_ON_ERROR),
                'default_value' => ['value' => [
                    'NGN' => 'paystack',
                    'GHS' => 'paystack',
                    'KES' => 'flutterwave',
                    'ZAR' => 'paystack',
                    'UGX' => 'flutterwave',
                    'TZS' => 'flutterwave',
                    'XOF' => 'flutterwave',
                    'XAF' => 'flutterwave',
                    'USD' => 'stripe',
                    'EUR' => 'stripe',
                    'GBP' => 'stripe',
                    'CAD' => 'stripe',
                    'AUD' => 'stripe',
                ]],
                'is_public' => false,
                'sort_order' => 3,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.provider_currencies',
                'label' => 'Enabled Provider Currencies',
                'description' => 'Deprecated: prefer payment_gateway_currencies pivots. Currencies enabled for each provider. Values are validated against provider capabilities.',
                'type' => SettingType::JSON,
                'value' => json_encode([
                    'paystack' => ['NGN', 'GHS', 'ZAR', 'USD'],
                    'flutterwave' => ['NGN', 'GHS', 'KES', 'UGX', 'TZS', 'ZAR', 'XAF', 'XOF', 'USD', 'EUR', 'GBP'],
                    'stripe' => ['NGN', 'GHS', 'KES', 'UGX', 'TZS', 'ZAR', 'XAF', 'XOF', 'USD', 'EUR', 'GBP', 'CAD', 'AUD'],
                ], JSON_THROW_ON_ERROR),
                'default_value' => ['value' => [
                    'paystack' => ['NGN', 'GHS', 'ZAR', 'USD'],
                    'flutterwave' => ['NGN', 'GHS', 'KES', 'UGX', 'TZS', 'ZAR', 'XAF', 'XOF', 'USD', 'EUR', 'GBP'],
                    'stripe' => ['NGN', 'GHS', 'KES', 'UGX', 'TZS', 'ZAR', 'XAF', 'XOF', 'USD', 'EUR', 'GBP', 'CAD', 'AUD'],
                ]],
                'options' => config('payments.provider_currencies'),
                'is_public' => false,
                'sort_order' => 4,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.default_currency',
                'label' => 'Default Billing Currency',
                'description' => 'Fallback currency when a country has no matching plan price. Prefer explicit plan prices per market.',
                'type' => SettingType::STRING,
                'value' => 'USD',
                'default_value' => ['value' => 'USD'],
                'is_public' => false,
                'sort_order' => 4,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.credentials_provider',
                'label' => 'Edit Provider Credentials',
                'description' => 'Choose which payment provider credentials to edit below. Secrets are stored encrypted.',
                'type' => SettingType::SELECT,
                'value' => 'paystack',
                'default_value' => ['value' => 'paystack'],
                'options' => ['paystack', 'flutterwave', 'stripe'],
                'is_public' => false,
                'sort_order' => 5,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.paystack_public',
                'label' => 'Paystack Public Key',
                'description' => 'Deprecated: prefer payment_gateway_configs.public_key.',
                'type' => SettingType::STRING,
                'value' => null,
                'default_value' => ['value' => null],
                'sort_order' => 6,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.paystack_secret',
                'label' => 'Paystack Secret Key',
                'description' => 'Deprecated: prefer payment_gateway_configs.secret_key.',
                'type' => SettingType::ENCRYPTED,
                'value' => null,
                'default_value' => ['value' => null],
                'is_encrypted' => true,
                'sort_order' => 7,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.paystack_webhook_secret',
                'label' => 'Paystack Webhook Secret',
                'description' => 'Deprecated: prefer payment_gateway_configs.webhook_secret.',
                'type' => SettingType::ENCRYPTED,
                'value' => null,
                'default_value' => ['value' => null],
                'is_encrypted' => true,
                'sort_order' => 8,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.flutterwave_public',
                'label' => 'Flutterwave Public Key',
                'description' => 'Deprecated: prefer payment_gateway_configs.public_key.',
                'type' => SettingType::STRING,
                'value' => null,
                'default_value' => ['value' => null],
                'sort_order' => 9,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.flutterwave_secret',
                'label' => 'Flutterwave Secret Key',
                'description' => 'Deprecated: prefer payment_gateway_configs.secret_key.',
                'type' => SettingType::ENCRYPTED,
                'value' => null,
                'default_value' => ['value' => null],
                'is_encrypted' => true,
                'sort_order' => 10,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.flutterwave_webhook_secret',
                'label' => 'Flutterwave Webhook Secret',
                'description' => 'Deprecated: prefer payment_gateway_configs.webhook_secret.',
                'type' => SettingType::ENCRYPTED,
                'value' => null,
                'default_value' => ['value' => null],
                'is_encrypted' => true,
                'sort_order' => 11,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.stripe_publishable',
                'label' => 'Stripe Publishable Key',
                'description' => 'Deprecated: prefer payment_gateway_configs.public_key.',
                'type' => SettingType::STRING,
                'value' => null,
                'default_value' => ['value' => null],
                'sort_order' => 12,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.stripe_secret',
                'label' => 'Stripe Secret Key',
                'description' => 'Deprecated: prefer payment_gateway_configs.secret_key.',
                'type' => SettingType::ENCRYPTED,
                'value' => null,
                'default_value' => ['value' => null],
                'is_encrypted' => true,
                'sort_order' => 13,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.stripe_webhook_secret',
                'label' => 'Stripe Webhook Secret',
                'description' => 'Deprecated: prefer payment_gateway_configs.webhook_secret.',
                'type' => SettingType::ENCRYPTED,
                'value' => null,
                'default_value' => ['value' => null],
                'is_encrypted' => true,
                'sort_order' => 14,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.signup_card_verification',
                'label' => 'Require Card Verification at Signup',
                'description' => 'When enabled, self-serve signup must soft-verify a card before the tenant is created.',
                'type' => SettingType::BOOLEAN,
                'value' => '1',
                'default_value' => ['value' => true],
                'is_public' => false,
                'sort_order' => 15,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.card_verification_amount',
                'label' => 'Card Verification Amount',
                'description' => 'Amount charged for soft verification when the provider cannot tokenize at $0 (e.g. Paystack). Use at least 5.00 for NGN — Paystack rejects ₦1 with a misleading channel error.',
                'type' => SettingType::FLOAT,
                'value' => '50.00',
                'default_value' => ['value' => 50.0],
                'is_public' => false,
                'sort_order' => 16,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.card_verification_amounts',
                'label' => 'Card Verification Amounts',
                'description' => 'Soft-verification charge by ISO currency. Stripe uses a zero-charge setup regardless of this map.',
                'type' => SettingType::JSON,
                'value' => json_encode([
                    'NGN' => 50,
                    'GHS' => 1,
                    'KES' => 10,
                    'UGX' => 1000,
                    'TZS' => 1000,
                    'ZAR' => 5,
                    'XAF' => 500,
                    'XOF' => 500,
                    'USD' => 1,
                    'EUR' => 1,
                    'GBP' => 1,
                    'CAD' => 1,
                    'AUD' => 1,
                ], JSON_THROW_ON_ERROR),
                'default_value' => ['value' => [
                    'NGN' => 50,
                    'GHS' => 1,
                    'KES' => 10,
                    'UGX' => 1000,
                    'TZS' => 1000,
                    'ZAR' => 5,
                    'XAF' => 500,
                    'XOF' => 500,
                    'USD' => 1,
                    'EUR' => 1,
                    'GBP' => 1,
                    'CAD' => 1,
                    'AUD' => 1,
                ]],
                'is_public' => false,
                'sort_order' => 17,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.card_verification_minimums',
                'label' => 'Card Verification Minimums',
                'description' => 'Provider-specific minimum charge by ISO currency. Amounts below these values are rejected.',
                'type' => SettingType::JSON,
                'value' => json_encode([
                    'paystack' => ['NGN' => 5],
                    'flutterwave' => [],
                    'stripe' => [],
                ], JSON_THROW_ON_ERROR),
                'default_value' => ['value' => [
                    'paystack' => ['NGN' => 5],
                    'flutterwave' => [],
                    'stripe' => [],
                ]],
                'is_public' => false,
                'sort_order' => 18,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.card_verification_currency',
                'label' => 'Card Verification Currency Override',
                'description' => 'Optional ISO currency for verification. Leave empty to use the signup country currency.',
                'type' => SettingType::STRING,
                'value' => null,
                'default_value' => ['value' => null],
                'is_public' => false,
                'sort_order' => 19,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.card_verification_refund',
                'label' => 'Refund Verification Charge',
                'description' => 'After a successful non-zero verification charge, automatically refund it (soft verify).',
                'type' => SettingType::BOOLEAN,
                'value' => '1',
                'default_value' => ['value' => true],
                'is_public' => false,
                'sort_order' => 20,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.invoice_due_days',
                'label' => 'Invoice Due Days',
                'description' => 'Default number of days customers have to pay a newly issued invoice.',
                'type' => SettingType::INTEGER,
                'value' => (int) config('billing.invoice_due_days', 7),
                'default_value' => ['value' => (int) config('billing.invoice_due_days', 7)],
                'options' => ['min' => 0, 'max' => 365, 'unit' => 'days'],
                'sort_order' => 21,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.past_due_grace_days',
                'label' => 'Past-Due Grace Days',
                'description' => 'Default access grace period after a subscription becomes past due.',
                'type' => SettingType::INTEGER,
                'value' => (int) config('billing.past_due_grace_days', 3),
                'default_value' => ['value' => (int) config('billing.past_due_grace_days', 3)],
                'options' => ['min' => 0, 'max' => 90, 'unit' => 'days'],
                'sort_order' => 22,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.trial_reminder_days',
                'label' => 'Trial Reminder Days',
                'description' => 'How many days before trial end to send the conversion reminder.',
                'type' => SettingType::INTEGER,
                'value' => (int) config('billing.trial_reminder_days', 3),
                'default_value' => ['value' => (int) config('billing.trial_reminder_days', 3)],
                'options' => ['min' => 1, 'max' => 30, 'unit' => 'days'],
                'sort_order' => 23,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.checkout_link_ttl_hours',
                'label' => 'Checkout Link Lifetime',
                'description' => 'Lifetime in hours for signed trial-conversion checkout links.',
                'type' => SettingType::INTEGER,
                'value' => (int) config('billing.checkout_link_ttl_hours', 72),
                'default_value' => ['value' => (int) config('billing.checkout_link_ttl_hours', 72)],
                'options' => ['min' => 1, 'max' => 720, 'unit' => 'hours'],
                'sort_order' => 24,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.invoice_link_ttl_hours',
                'label' => 'Invoice Link Lifetime',
                'description' => 'Lifetime in hours for signed public invoice payment links.',
                'type' => SettingType::INTEGER,
                'value' => (int) config('billing.invoice_link_ttl_hours', 168),
                'default_value' => ['value' => (int) config('billing.invoice_link_ttl_hours', 168)],
                'options' => ['min' => 1, 'max' => 2160, 'unit' => 'hours'],
                'sort_order' => 25,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.default_interval',
                'label' => 'Default Billing Interval',
                'description' => 'Initial interval for new plan and price drafts.',
                'type' => SettingType::SELECT,
                'value' => (string) config('billing.default_interval', 'monthly'),
                'default_value' => ['value' => (string) config('billing.default_interval', 'monthly')],
                'options' => ['monthly', 'quarterly', 'yearly'],
                'sort_order' => 26,
            ],
            [
                'group' => SettingGroup::Billing,
                'key' => 'billing.price_fallback_mode',
                'label' => 'Price Fallback Mode',
                'description' => 'Controls how far price resolution may fall back when an exact market price is unavailable.',
                'type' => SettingType::SELECT,
                'value' => (string) config('billing.price_fallback_mode', 'any_active'),
                'default_value' => ['value' => (string) config('billing.price_fallback_mode', 'any_active')],
                'options' => ['exact_currency', 'default_currency', 'same_interval', 'any_active'],
                'sort_order' => 27,
            ],
            [
                'group' => SettingGroup::Invoice,
                'key' => 'invoice.company_name',
                'label' => 'Company Name',
                'description' => 'Business name shown on the invoice header.',
                'type' => SettingType::STRING,
                'value' => 'Multi Tenant API',
                'default_value' => ['value' => 'Multi Tenant API'],
                'is_public' => true,
                'sort_order' => 1,
            ],
            [
                'group' => SettingGroup::Invoice,
                'key' => 'invoice.logo_url',
                'label' => 'Logo URL',
                'description' => 'Publicly accessible URL of the company logo displayed on invoices.',
                'type' => SettingType::URL,
                'value' => null,
                'default_value' => ['value' => null],
                'is_public' => true,
                'sort_order' => 2,
            ],
            [
                'group' => SettingGroup::Invoice,
                'key' => 'invoice.company_email',
                'label' => 'Company Email',
                'description' => 'Billing contact email shown on the invoice.',
                'type' => SettingType::EMAIL,
                'value' => 'billing@example.com',
                'default_value' => ['value' => 'billing@example.com'],
                'is_public' => true,
                'sort_order' => 3,
            ],
            [
                'group' => SettingGroup::Invoice,
                'key' => 'invoice.company_phone',
                'label' => 'Company Phone',
                'description' => 'Contact phone number shown on the invoice.',
                'type' => SettingType::STRING,
                'value' => null,
                'default_value' => ['value' => null],
                'is_public' => true,
                'sort_order' => 4,
            ],
            [
                'group' => SettingGroup::Invoice,
                'key' => 'invoice.company_website',
                'label' => 'Company Website',
                'description' => 'Website URL shown on the invoice.',
                'type' => SettingType::URL,
                'value' => null,
                'default_value' => ['value' => null],
                'is_public' => true,
                'sort_order' => 5,
            ],
            [
                'group' => SettingGroup::Invoice,
                'key' => 'invoice.company_address',
                'label' => 'Company Address',
                'description' => 'Full business address shown in the invoice header.',
                'type' => SettingType::TEXTAREA,
                'value' => null,
                'default_value' => ['value' => null],
                'is_public' => true,
                'sort_order' => 6,
            ],
            [
                'group' => SettingGroup::Invoice,
                'key' => 'invoice.company_tax_id',
                'label' => 'Tax / VAT ID',
                'description' => 'Business tax or VAT identification number.',
                'type' => SettingType::STRING,
                'value' => null,
                'default_value' => ['value' => null],
                'is_public' => true,
                'sort_order' => 7,
            ],
            [
                'group' => SettingGroup::Invoice,
                'key' => 'invoice.number_prefix',
                'label' => 'Invoice Number Prefix',
                'description' => 'Prefix displayed before the invoice number (e.g. INV-).',
                'type' => SettingType::STRING,
                'value' => (string) config('billing.invoice_number_prefix', 'INV-'),
                'default_value' => ['value' => (string) config('billing.invoice_number_prefix', 'INV-')],
                'options' => ['min_length' => 1, 'max_length' => 12, 'pattern' => 'letters, numbers, hyphens, underscores'],
                'is_public' => true,
                'sort_order' => 8,
            ],
            [
                'group' => SettingGroup::Invoice,
                'key' => 'invoice.footer_note',
                'label' => 'Footer Note',
                'description' => 'Payment terms or thank-you note shown at the bottom of the invoice.',
                'type' => SettingType::TEXTAREA,
                'value' => 'Thank you for your business.',
                'default_value' => ['value' => 'Thank you for your business.'],
                'is_public' => true,
                'sort_order' => 9,
            ],
            [
                'group' => SettingGroup::Tenant,
                'key' => 'tenant.default_trial_days',
                'label' => 'Default Trial Days',
                'description' => 'Fallback trial duration for tenant creation outside a plan-backed signup.',
                'type' => SettingType::INTEGER,
                'value' => 14,
                'default_value' => ['value' => 14],
                'sort_order' => 1,
            ],
            [
                'group' => SettingGroup::Tenant,
                'key' => 'tenant.owner_invite_ttl_hours',
                'label' => 'Owner Invitation Expiry',
                'description' => 'Number of hours a tenant owner setup invitation remains valid.',
                'type' => SettingType::INTEGER,
                'value' => 72,
                'default_value' => ['value' => 72],
                'sort_order' => 2,
            ],
            [
                'group' => SettingGroup::Tenant,
                'key' => 'tenant.signup_intent_ttl_hours',
                'label' => 'Signup Session Expiry',
                'description' => 'Number of hours an unfinished signup and card verification session remains valid.',
                'type' => SettingType::INTEGER,
                'value' => 2,
                'default_value' => ['value' => 2],
                'sort_order' => 3,
            ],
            [
                'group' => SettingGroup::Tenant,
                'key' => 'tenant.auto_generate_domain',
                'label' => 'Automatically Generate Primary Domain',
                'description' => 'Create a slug-based primary domain when a tenant with an owner email has no supplied domain.',
                'type' => SettingType::BOOLEAN,
                'value' => true,
                'default_value' => ['value' => true],
                'sort_order' => 4,
            ],
            [
                'group' => SettingGroup::Tenant,
                'key' => 'tenant.default_force_https',
                'label' => 'Force HTTPS on New Domains',
                'description' => 'Enable HTTPS enforcement by default when a tenant domain is attached.',
                'type' => SettingType::BOOLEAN,
                'value' => true,
                'default_value' => ['value' => true],
                'sort_order' => 5,
            ],
            [
                'group' => SettingGroup::Tenant,
                'key' => 'tenant.allow_custom_domains',
                'label' => 'Allow Custom Domains',
                'description' => 'Platform-wide switch for attaching custom tenant domains. Plan entitlements still apply separately.',
                'type' => SettingType::BOOLEAN,
                'value' => true,
                'default_value' => ['value' => true],
                'sort_order' => 6,
            ],
        ];
    }

    private function normalizePaymentMode(string $mode): string
    {
        return in_array($mode, ['test', 'live'], true) ? $mode : 'test';
    }
}
